# Change these first
owner: OpenSourceSimon # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: My Website
    url: https://simonrijntjes.nl/
    
  - name: My WordPress
    url: https://simonrijntjes.nl/wordpress/
    
  - name: Twingate
    url: $TWINGATE
    
  - name: Synology QuickConnect
    url: $SYNOLOGY
        
  - name: Unsplash API
    url: https://source.unsplash.com/random/3840x2160/?nature
    maxResponseTime: 2500
    __dangerous__body_down: "error"
    
  - name: Quotable API
    url: https://api.quotable.io/random
    
  - name: Reddit Bot Documentation
    url: https://reddit-video-maker-bot.netlify.app/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "*/2 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 * * * *"
  uptime: "*/2 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
