# Change these first
owner: OpenSourceSimon # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: My Website
    url: https://simonrijntjes.nl/
    maxResponseTime: 5000
    
  - name: My WordPress
    url: https://simonrijntjes.nl/wordpress/
    icon: https://s1.wp.com/i/favicon.ico
    
  - name: Twingate
    url: $TWINGATE
    maxResponseTime: 5000
    icon: https://www.twingate.com/favicon-32x32.png?v=3e6e4cc23bdfc2e232c3549c76c75d21
    
  - name: Synology QuickConnect
    url: $SYNOLOGY
    maxResponseTime: 2500
    icon: https://www.synology.com/img/icon/favicon@2x.png

  - name: Vercel Good Morning Tech
    url: https://goodmorningtech.vercel.app/
    
  - name: Database Good Morning Tech
    url: https://www.elephantsql.com/
        
  - name: Unsplash API
    url: https://source.unsplash.com/random/3840x2160/?nature
    maxResponseTime: 2500
    __dangerous__body_down: "error"
    icon: https://unsplash.com/favicon-32x32.png
    
  - name: Quotable API
    url: https://api.quotable.io/random
    maxResponseTime: 5000
    
  - name: Reddit Bot Documentation
    url: https://reddit-video-maker-bot.netlify.app/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "*/2 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/2 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
